CREATE TABLE Final(
	Id INT NOT NULL,
	EquipeA VARCHAR(100) NOT NULL,
	EquipeB VARCHAR(100) NOT NULL,
	TokenA VARCHAR(50) NOT NULL,
	TokenB VARCHAR(50) NOT NULL,
	GolsEquipeA INT NOT NULL,
	GolsEquipeB INT NOT NULL,
	GolsPenaltyEquipeA INT NOT NULL,
	GolsPenaltyEquipeB INT NOT NULL,
	Data  DATETIME NOT NULL,
	PRIMARY KEY(Id)
);