INSERT INTO SELECAO(NOME,TOKEN)VALUES('Catar',newId());
INSERT INTO dbo.selecao(nome, token)Values('Argentina',newId())
INSERT INTO dbo.selecao(nome, token)Values('Brasil',newId())
INSERT INTO dbo.selecao(nome, token)Values('Inglaterra',newId())
INSERT INTO dbo.selecao(nome, token)Values('França',newId())
INSERT INTO dbo.selecao(nome, token)Values('Espanha',newId())
INSERT INTO dbo.selecao(nome, token)Values('Belgica',newId())
INSERT INTO dbo.selecao(nome, token)Values('Portugal',newId())
INSERT INTO dbo.selecao(nome, token)Values('Alemanha',newId())
INSERT INTO dbo.selecao(nome, token)Values('Holanda',newId())
INSERT INTO dbo.selecao(nome, token)Values('Uruguai',newId())
INSERT INTO dbo.selecao(nome, token)Values('Croácia',newId())
INSERT INTO dbo.selecao(nome, token)Values('Dinamarca',newId())
INSERT INTO dbo.selecao(nome, token)Values('México',newId())
INSERT INTO dbo.selecao(nome, token)Values('Estados Unidos',newId())
INSERT INTO dbo.selecao(nome, token)Values('Senegal',newId())
INSERT INTO dbo.selecao(nome, token)Values('País de Gales',newId())
INSERT INTO dbo.selecao(nome, token)Values('Polônia',newId())
INSERT INTO dbo.selecao(nome, token)Values('Austrália',newId())
INSERT INTO dbo.selecao(nome, token)Values('Japão',newId())
INSERT INTO dbo.selecao(nome, token)Values('Marrocos',newId())
INSERT INTO dbo.selecao(nome, token)Values('Suíça',newId())
INSERT INTO dbo.selecao(nome, token)Values('Gana',newId())
INSERT INTO dbo.selecao(nome, token)Values('Coreia do Sul',newId())
INSERT INTO dbo.selecao(nome, token)Values('Camarões',newId())
INSERT INTO dbo.selecao(nome, token)Values('Sérvia',newId())
INSERT INTO dbo.selecao(nome, token)Values('Canadá',newId())
INSERT INTO dbo.selecao(nome, token)Values('Costa Rica',newId())
INSERT INTO dbo.selecao(nome, token)Values('Tunísia',newId())
INSERT INTO dbo.selecao(nome, token)Values('Arábia Sudita',newId())
INSERT INTO dbo.selecao(nome, token)Values('Irã',newId())
INSERT INTO dbo.selecao(nome, token)Values('Equador',newId())